version: '3'

services:
  db:
    container_name: db
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: justask-ai-db
    volumes:
      - ./mongo:/data/db